services:
  - type: web
    name: atilim-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT atilim_api:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
