services:
  - type: web
    name: atilim-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn atilim_api:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
