services:
  - type: web
    name: atilim-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python atilim_api.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
